{%set name = "SpeechRecognition" %}
{%set version = "3.6.0" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "22391df1c5e2b4d9b9ac423e4fa29b96c99f83142fc4d06d627c0af67f4f67d7" %}
{%set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - speech_recognition

about:
  home: https://github.com/Uberi/speech_recognition
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Library for performing speech recognition, with support for several engines and APIs, online and offline.'
  dev_url: https://github.com/Uberi/speech_recognition

extra:
  recipe-maintainers:
    - pmlandwehr
