{% set name = "SpeechRecognition" %}
{% set version = "3.6.1" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "d99949d61221ff44fd328b61e88b75a44103ca58da5dd948a8f388b3cec5057e" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash}}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - speech_recognition

about:
  home: https://github.com/Uberi/speech_recognition
  license_file: LICENSE.txt
  license: BSD 3-Clause
  license_family: BSD
  summary: 'Library for performing speech recognition, with support for several engines and APIs, online and offline.'
  dev_url: https://github.com/Uberi/speech_recognition

extra:
  recipe-maintainers:
    - pmlandwehr
