travis:
  secure:
    BINSTAR_TOKEN: SRYxQWhQ3a5JXfcv7f6LPGKpfSQQjlmL8cXnkcfpnE6m2WbMRRCjAyYsJskuUHvJ0guUAo9foqi6UHHWzA7+K0PUqb9DEzcm1TIFGkmDnD4oUKQt/26TxpbgHVessOw+M6TYvo7mm2M+u62DdWXuFJids+3eDG0WJIcAwP+WI7Kdvi1D8338XS6EqTTTB0VyCgx6DJVl5ea5nkmvzZ8kfgu/nnG4HWj/fgi/YMm+5vG3IaSutWf2TPWHxMsSjYS0DDjvilKF14Si0e8LBJwtVtLWC8raAKY0eWelTe79RrZpVK8pBNaByT4ArIUU0dkklwYAwKadB+dpSaxkiASYZ8Fw5eHLi8KnLzAfJTG7cA/l3KBuxfMWjn9Ja5XF/L6CY1TZrG+ER/AYMUXDQLKRuHl+E/Rfgkjhg+oOP+fWkh5RSl3JKYf9Rx2XFLpwNoeOAheonOLV2TBE32haaqf1NEWRKglKiQjhYMRorAP6NjAoZ88JBloaX3aHPPLhiawnkKh6n0QJWloOVcf7eCoLyWWQQ+UXI3EZcgR1v0grKRAQFeonNuiq5UtR3bIk4ZicpfTR7IIQjziJ8tX73E8rjfWtxIKter2wGoFVGHw29KM0fsyqYQ4XwWOMOiUW0jnfId5e8wCniSpl6+ZGJc96FE468EvafdSU08FjYgmzdwY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
